SEN-2525 Recipes for Migration from Joda-Time DateTimeFormat and DateTimeFormatter
SecureCodeWarrior/sensei-recipes pull request #29
Opened 2021-11-11 04:09 UTC by wanderneto

This pull request contains recipes for migration of org.joda.time.format.DateTimeFormatter to java.time

The focus of this pull request is on recipes that are specific to DateTimeFormatter migration.

Co-authored-by: Cameron Gregor cgregor@securecodewarrior.com

2021-11-12 00:13 UTC, camac requested changes
The recipes themselves are Looking good I think we just need to add some documentation and some minor changes to tests/examples

2021-11-12 00:13 UTC, camac commented on example_code/joda-time-to-java-time-examples/src/main/java/formatting/DateTimeFormatterExamples.java
> +    }
I'm thinking maybe we just get rid of these, and instead use the tests to demonstrate all this.
I was originally thinking this was a good 'playground' to test against but it is too clunky

2021-11-12 00:13 UTC, camac commented on recipes/Java/JodaTimeToJavaTime/DateTimeFormatter/Methods/Datetimeformatter-parsemillis.yaml
> +- name: Rewrite parseMillis to java.time equivalent - DateTime
We will also need a fix here for when we parse a string that already contains a zone in it.

e.g. when we use an ISO formatter for parsing such as https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html#ISO_ZONED_DATE_TIME
 
it will already have a zone in there, then we can probably use ZonedDateTime.parse 

Same thing for:
https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html#ISO_OFFSET_DATE_TIME

OffsetDateTime.parse

2021-11-12 00:13 UTC, camac commented on recipes/Java/JodaTimeToJavaTime/DateTimeFormatter/Datetimeformatter-print-long.yaml
> +      to: '{{{ qualifier }}}.format(java.time.ZonedDateTime.ofInstant(java.time.Instant.ofEpochMilli({{{ arguments }}}), java.time.ZoneId.systemDefault()))'
Maybe we can add a test to cover this print(long) example. I think it is similar to the test that is already there for the long, appendable

2021-11-12 09:30 UTC, bbogason requested changes
Looks good!

Requesting changes because of spelling mistake in Datetimeformatter-chronolgy.yaml file. Feel free to merge once that is fixed.

2021-11-12 09:30 UTC, bbogason commented on example_code/joda-time-to-java-time-examples/src/test/java/formatting/DateTimeFormatFormatTest.java
> +public class DateTimeFormatFormatTest {
Minor: JUnit5 test classes and methods don't need to be public, so the convention is to use the default visibility (i.e. no modifier)

2021-11-12 09:30 UTC, bbogason commented on example_code/joda-time-to-java-time-examples/src/test/java/formatting/DateTimeFormatParseTest.java
> +        String expectedString = "8/10/21";
super minor: there is some ambiguity whether this is 8th of October, or 10th of August. By reading other tests I can see that this is October 8th, but perhaps it would be clearer if we chose another date where there was less ambiguity, such as anything after the 12th.

"14/10/21" can only be interpreted as 14th of October (if we ignore the improbable interpretation that it's the 21st October 2014) 😅

2021-11-12 09:30 UTC, bbogason commented on recipes/Java/JodaTimeToJavaTime/DateTimeFormat/Datetimeformat-fullDate.yaml
> +scopes: {}
consider omitting, ditto for other recipes

2021-11-12 09:30 UTC, bbogason commented on recipes/Java/JodaTimeToJavaTime/DateTimeFormatter/Datetimeformatter-printto-readable-appendable.yaml
> +      to: '{{{ qualifier }}}.formatTo({{{ arguments.1 }}},{{{ arguments.0 }}})'
minor: missing space after comma
ditto in other recipes

Or will Sensei add the missing space when applying the quickfix? in which case you can ignore this.

2021-11-12 09:30 UTC, bbogason commented on recipes/Java/JodaTimeToJavaTime/DateTimeFormatter/Methods/Datetimeformatter-chronolgy.yaml
> +    name: getChronolgy
this looks like a spelling mistake. (ditto in the name of this file).

Are you sure this recipe is actually matching anything? Or are we missing a "test case"?

2021-11-12 09:30 UTC, bbogason commented on recipes/Java/JodaTimeToJavaTime/DateTimeFormatter/Methods/Datetimeformatter-noequivalent.yaml
> +    There are some methods from org.joda.time.format.DateTimeFormatter that there is no equivalent mehtod in java.time.
```suggestion
    There are some methods from org.joda.time.format.DateTimeFormatter that have no equivalent in java.time.
```

or at least fix the spelling mistake in the word "mehtod": "method"

2021-11-12 09:30 UTC, bbogason commented on recipes/Java/JodaTimeToJavaTime/DateTimeFormatter/Methods/Datetimeformatter-parseDateTime.yaml
> +    This recipe is designed to match on broken code. This method originally was called by org.joda.time.format.DateTimeFormatter type, however this object type should first be migrated to java.time.f
consider adding line-breaks to this very long line. maybe aim for 70-80 max length?  
Ditto in other recipes.

2021-11-12 09:36 UTC, bbogason approved these changes
Looks good to me! Approved.

2021-11-12 09:36 UTC, bbogason commented on recipes/Java/JodaTimeToJavaTime/DateTimeFormatter/Methods/Datetimeformatter-chronolgy.yaml
> +    name: getChronolgy
Oops, I see now that this was a spelling mistake in joda-time library. Carry on 😄

2021-11-15 02:42 UTC, wanderneto commented on recipes/Java/JodaTimeToJavaTime/DateTimeFormat/Datetimeformat-import.yaml
> +      to: import java.time.format.DateTimeFormatter;
I removed this as it no longer needed

2021-11-15 02:46 UTC, wanderneto commented on recipes/Java/JodaTimeToJavaTime/DateTimeFormatter/Datetimeformatter-print-long.yaml
> +  comment: "Searches for a print method called and provides fixes to migrate to a java.time equivalent.\n    \nThis recipe is designed to match on broken code. This method originally was called by or
Fixed

2021-11-15 02:53 UTC, wanderneto commented on example_code/joda-time-to-java-time-examples/src/test/java/formatting/DateTimeFormatParseTest.java
> +        String expectedString = "8/10/21";
Makes sense. I changed it to a date that is not ambiguous

2021-11-15 02:54 UTC, wanderneto commented on recipes/Java/JodaTimeToJavaTime/DateTimeFormatter/Methods/Datetimeformatter-noequivalent.yaml
> +    There are some methods from org.joda.time.format.DateTimeFormatter that there is no equivalent mehtod in java.time.
Thanks

2021-11-15 03:19 UTC, wanderneto commented on example_code/joda-time-to-java-time-examples/src/test/java/formatting/DateTimeFormatFormatTest.java
> +public class DateTimeFormatFormatTest {
Thanks for letting me know. I changed it to use default visibility

2021-11-15 03:33 UTC, wanderneto commented on recipes/Java/JodaTimeToJavaTime/DateTimeFormat/Datetimeformat-fullDate.yaml
> +scopes: {}
Done

2021-11-15 03:38 UTC, wanderneto commented on recipes/Java/JodaTimeToJavaTime/DateTimeFormatter/Datetimeformatter-printto-readable-appendable.yaml
> +      to: '{{{ qualifier }}}.formatTo({{{ arguments.1 }}},{{{ arguments.0 }}})'
I don't think Sensei will add this missing space. I fixed those files

2021-11-15 03:40 UTC, wanderneto commented on recipes/Java/JodaTimeToJavaTime/DateTimeFormatter/Methods/Datetimeformatter-chronolgy.yaml
> +    name: getChronolgy
Yep, this was a spelling mistake in joda-time, they created the proper method but the old one still exist (deprecated though)

2021-11-15 03:56 UTC, wanderneto commented on recipes/Java/JodaTimeToJavaTime/DateTimeFormatter/Datetimeformatter-print-long.yaml
> +      to: '{{{ qualifier }}}.format(java.time.ZonedDateTime.ofInstant(java.time.Instant.ofEpochMilli({{{ arguments }}}), java.time.ZoneId.systemDefault()))'
There are some tests using this rule. e. g. test_fullDate_is_equivalent

2021-11-15 04:49 UTC, wanderneto commented on recipes/Java/JodaTimeToJavaTime/DateTimeFormat/Datetimeformat-fullDate.yaml
> +  descriptionFile: descriptions/datetimeformat.html
Included 3 different files

2021-11-15 05:02 UTC, wanderneto commented on recipes/Java/JodaTimeToJavaTime/DateTimeFormatter/Methods/Datetimeformatter-parseDateTime.yaml
> +  descriptionFile: DateTimeFormatter/descriptions/datetimeformatter.html
Done

2021-11-15 05:03 UTC, wanderneto commented on example_code/joda-time-to-java-time-examples/src/main/java/formatting/DateTimeFormatterExamples.java
> +    }
Done

2021-11-15 05:03 UTC, wanderneto commented on example_code/joda-time-to-java-time-examples/src/test/java/formatting/DateTimeFormatParseTest.java
> +    }
I changed all tests in DateTimeFormatParseTest.java

2021-11-15 05:53 UTC, wanderneto commented on recipes/Java/JodaTimeToJavaTime/DateTimeFormatter/Methods/Datetimeformatter-parsemillis.yaml
> +- name: Rewrite parseMillis to java.time equivalent - DateTime
I created a test method that check this. See parsemillis_with_zone_is_equivalent on DateTimeFormatParseTest and let me know if it covers it

2021-11-15 05:53 UTC, wanderneto commented on recipes/Java/JodaTimeToJavaTime/DateTimeFormat/Datetimeformat-forPattern.yaml
> +  descriptionFile: descriptions/datetimeformat.html
Done. Thanks for the file

2021-11-15 06:58 UTC, wanderneto commented on recipes/Java/JodaTimeToJavaTime/DateTimeFormatter/Methods/Datetimeformatter-parseDateTime.yaml
> +    This recipe is designed to match on broken code. This method originally was called by org.joda.time.format.DateTimeFormatter type, however this object type should first be migrated to java.time.f
Done

2021-11-16 04:41 UTC, merged