SEN-2541 Recipes for migrating common 'get' methods for Joda-Time to java.time
SecureCodeWarrior/sensei-recipes pull request #30
Opened 2021-11-17 06:33 UTC by camac

Closes SEN-2541

This set of recipes covers the migration of some methods that are common
to a range of java.time classes.

Tests that demonstrate and support the logic of the recipes are included
in CommonGetMethodsTest.

Note: the DateTime getMillis recipe is also included, I originally
thought this would be a common method but it is really only for DateTime
and it's corresponding java.time objects. I have included it anyway but
it is in the DateTime folder to reflect it is only for DateTime migration.

2021-11-17 09:16 UTC, bbogason requested changes
One copy paste error, otherwise looks good!

2021-11-17 09:16 UTC, bbogason commented on recipes/Java/JodaTimeToJavaTime/Common/get/descriptions/getYearOfCentury.html
> +<h1>getCenturyOfEra() is not available in java.time</h1>
copy paste error?

This should be getYearOfCentury(), ditto elsewhere in this file

2021-11-17 09:16 UTC, bbogason commented on recipes/Java/JodaTimeToJavaTime/DateTime/DateTime-getMillis.yaml
> +  comment: "Joda-time DateTime provided a getMillis() method used to get the Milliseconds since Epoch.\nIn java.time this method is no longer available. \nTo achieve the same result you can first con
block comment

2021-11-17 22:43 UTC, camac commented on recipes/Java/JodaTimeToJavaTime/Common/get/descriptions/getYearOfCentury.html
> +<h1>getCenturyOfEra() is not available in java.time</h1>
🤦  When I copy/paste I usually feel unsettled until I have double checked every thing. I thought I'd double checked everything, sorry about that! Thanks for catching this one!

2021-11-17 22:45 UTC, camac commented on recipes/Java/JodaTimeToJavaTime/DateTime/DateTime-getMillis.yaml
> +  comment: "Joda-time DateTime provided a getMillis() method used to get the Milliseconds since Epoch.\nIn java.time this method is no longer available. \nTo achieve the same result you can first con
Nice pickup - I thought I had double checked all comments as well but maybe I missed this one because I put in under the DateTime folder.
Fixed.

2021-11-18 05:58 UTC, bbogason approved these changes
👍

2021-11-18 05:58 UTC, bbogason commented on recipes/Java/JodaTimeToJavaTime/Common/get/descriptions/getYearOfCentury.html
> +<p>This recipe will replace the getYearOfCentury method call, with an equivalent calculation which is based on the logic used in Joda-Time to calculate century of era.<p>
```suggestion
<p>This recipe will replace the getYearOfCentury method call, with an equivalent calculation which is based on the logic used in Joda-Time to calculate year of century.<p>
```

?

2021-11-18 06:57 UTC, camac commented on recipes/Java/JodaTimeToJavaTime/Common/get/descriptions/getYearOfCentury.html
> +<p>This recipe will replace the getYearOfCentury method call, with an equivalent calculation which is based on the logic used in Joda-Time to calculate century of era.<p>
Thanks again! I promise no more will get through 😄

2021-11-18 06:59 UTC, merged