SEN-2590 Add recipes for migrating Hamcrest size assertions to AssertJ
SecureCodeWarrior/sensei-recipes pull request #46
Opened 2021-12-14 16:08 UTC by bbogason

2021-12-14 22:42 UTC, bbogason commented on recipes/Java/AssertJ/From Hamcrest/Hamcrest_hasSize.yaml
> +  name: Change to assertThat(actual).isEqualTo(expected)
```suggestion
  name: Change to assertThat(actual).hasSize(expectedSize)
```

Similar elsewhere

2021-12-15 00:18 UTC, camac requested changes
I like how you have covered so many situations with just 2 recipes!

The only changes required are the updates to the fix names, I have added the other 3 suggested changes to the fix names (following on from your first suggested change).

2021-12-15 00:18 UTC, camac commented on recipes/Java/AssertJ/From Hamcrest/Hamcrest_hasSize.yaml
> +  name: Change to assertThat(actual).as(reason).isEqualTo(expected)
```suggestion
  name: Change to assertThat(actual).as(reason).hasSize(expectedSize)
```

2021-12-15 00:18 UTC, camac commented on recipes/Java/AssertJ/From Hamcrest/Hamcrest_isHasSize.yaml
> +  name: Change to assertThat(actual).isEqualTo(expected)
```suggestion
  name: Change to assertThat(actual).hasSize(expectedSize)
```

2021-12-15 00:18 UTC, camac commented on recipes/Java/AssertJ/From Hamcrest/Hamcrest_isHasSize.yaml
> +  name: Change to assertThat(actual).as(reason).isEqualTo(expected)
```suggestion
  name: Change to assertThat(actual).as(reason).hasSize(expectedSize)
```

2021-12-15 00:44 UTC, wanderneto approved these changes
They looked fine. Maybe just change the fixes names as @camac suggested, then the name will reflect exactly which method will be used.

2021-12-15 16:05 UTC, bbogason commented
> I like how you have covered so many situations with just 2 recipes!

Yes...
- I find Hamcrest a bit infuriating because there are so many ways of achieving the same thing.
- Ideally I would have only written a single recipe, but that lead to a recipe that even I could no longer follow or possibly maintain.

2021-12-15 16:07 UTC, merged